services:
  - type: web
    name: hello-agent-alp-kiro
    runtime: docker
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: AGENT_CARD_PATH
        value: agent.alp.json
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: SEED_KNOWLEDGE_DB
        value: "false"
